export const USER_DETAILS = 'USER_DETAILS';
export const SET_USER = 'SET_USER';
export const SET_NEW_USER = 'SET_NEW_USER';
export const SET_BOOKING_DETAILS = 'SET_BOOKING_DETAILS';
export const DELETE_BOOKING_DETAIL = 'DELETE_BOOKING_DETAIL';